name: Docker Image CI

on: [push]

env:
  DOCKER_IMAGE_NAME: ghcr.io/bayrakmustafa/codesigner:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Image Name
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/bayrakmustafa/codesigner:${{ github.ref_name }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push Docker Image to Github Package Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          platforms: linux/amd64

  test:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Image Name
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/bayrakmustafa/codesigner:${{ github.ref_name }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Pull Docker image to Github package registry
        run: docker pull ${{ env.DOCKER_IMAGE_NAME }}

      - name: Create Artifacts Directory
        shell: bash
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifacts

      - name: Sign Example PS1 File
        run: docker run -i --rm --volume ${GITHUB_WORKSPACE}/artifacts:/codesign/output --env-file .env ${{ env.DOCKER_IMAGE_NAME }} sign -input_file_path=/codesign/examples/codesign.ps1 -output_dir_path=/codesign/output

      - name: Upload Signed Files
        uses: actions/upload-artifact@v2
        with:
          name: codesign.ps1
          path: ./artifacts/codesign.ps1
